// <auto-generated />
namespace Service.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DKH_JXS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DKH_JXS));
        
        string IMigrationMetadata.Id
        {
            get { return "201706280452537_DKH_JXS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
